name: '42 Norminette'
description: 'Check 42 Norm with norminette linter'
author: 'Reach <reach@42paris.fr>'
branding:
  icon: 'activity'
  color: 'gray-dark'

inputs:
  flags:
    description: 'Flags passed to norminette'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'docker://alexandregv/norminette:v3'
  args:
    - ${{ inputs.flags }}