# This is a basic workflow to help you get started with Actions

name: '42 Norminette'
description: 'Check 42 Norm with norminette linter'
author: 'Reach <reach@42paris.fr>'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
branding:
  icon: 'activity'
  color: 'gray-dark'

inputs:
  flags:
    description: 'Flags passed to norminette'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'docker://alexandregv/norminette:v3'
  args:
    - ${{ inputs.flags }}
